name: map_package
description: A new Flutter project.
version: 0.1.7

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  qareeb_models:
    git:
      url: https://github.com/saedAlHanash/qareeb_models


  image_multi_type:
    git:
      url: https://github.com/saedAlHanash/image_multi_type

  m_cubit:
    git:
      url: https://github.com/saedAlHanash/m_cubit


  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: master
#  image_multi_type:
#    path: ../image_multi_type
#
#  qareeb_models:
#    path: ../qareeb_models



#  drawable_text:
#    path: ../drawable_text




  google_maps_flutter: ^2.9.0
  flutter_bloc: any

  widget_to_marker: ^1.0.6

  get_it: any
  http: any
  logger: any

  geolocator: any
  collection: any
  flutter_screenutil: any
  google_polyline_algorithm: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/icons/
    - assets/icons/restaurant.png
    - assets/

